Sprint 2
toropanov/middle.messenger.praktikum.yandex pull request #2
Opened 2022-12-04 20:15 UTC by toropanov

2022-12-05 10:43 UTC, podlovchenko requested changes
Привет, есть некоторые замечания по работе
1. В проекте используется yarn для запуска, но почему-то в репозиторий добавлен package-lock.json, его следует удалить и оставить yarn.lock
2. Много ошибок типизации, попробуй выполнить команду `tsc --noEmit`
3. Регулярка для логина немного не соответствует заданию, по заданию можно вводить - и _

2022-12-05 10:43 UTC, podlovchenko commented on src/styles.scss
> +      input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-12-05 10:43 UTC, podlovchenko commented on src/styles.scss
> +    background: #3369F3;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту, придерживаться одной цветовой палитры

2022-12-05 10:43 UTC, podlovchenko commented on src/styles.scss
> +}
Было бы отлично разделить стили и положить рядом с компонентами, в которых они используются, будет проще ориентироваться в стилях и поддерживать их

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/Block.ts
> +export default class Block {
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/Block.ts
> +export default class Block {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/Block.ts
> +  _addEvents() {
Для приватных методов не хватает модификатора private

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/HttpRequester.ts
> +    headers: customHeaders = {},
Приватный метод request поддерживает передачу заголовкой, но ни один из публичных методов
Необходимо добавить поддержку в публичные методы

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/HttpRequester.ts
> +    async = true
Стоит определить тип для возможных параметров и переиспользовать

2022-12-05 10:43 UTC, podlovchenko commented on src/utils/HttpRequester.ts
> +    async = true
Также стоит добавить поддержку timeout для запроса

2022-12-05 12:57 UTC, toropanov commented on src/styles.scss
> +}
Я пробовал такой подход, честно признаться несколько сложнее стало наоборот(

2022-12-05 15:24 UTC, toropanov commented on src/utils/Block.ts
> +export default class Block {
Добавил в TODO, так как сейчас разбираюсь с событийными моделями и TS

2022-12-06 08:35 UTC, podlovchenko requested changes
Привет, `Record<string, unknown>` немногим лучше any, не очень информативный тип, он не говорит о том какие поля можно передавать, и не поможет избежать ошибок, стоит все-таки описать более подробный типы для классов и аргументов функций
Также стоит помнить, что использование any, ts-ignore и as не лучшие практики

2022-12-06 12:27 UTC, toropanov reviewed
Добавил типы для каждого компонента и страницы, в фетч реквестер. Поправил все тесты и ввел для удобства агрегатор тестов yarn tests.

В третьем спринте предстоит небольшой рефакторинг Block в том числе)

2022-12-06 13:12 UTC, podlovchenko reviewed
Спасибо за правки, работу принимаю)

2022-12-10 08:55 UTC, merged