Sprint 3
toropanov/middle.messenger.praktikum.yandex pull request #3
Opened 2023-01-23 11:45 UTC by toropanov

# Yandex Practicum Task

[Swagger](https://ya-praktikum.tech/api/v2/swagger/)
[Socket](https://ya-praktikum.tech/api/v2/openapi/ws)

Разработка проекта в рамках обучения Яндекс Практикум.

## Установка

- `yarn start` — сборка и запуск проекта,
- `yarn dev` — запуск версии для разработчика,
- `yarn build` — сборка стабильной версии.

- `yarn stylelint` -  Проверка Stylelint
- `yarn eslint` — Проверка ESLint
- `yarn typescript` - Проверка TypeScript

- `yarn errors` - Проверка всех ошибок разом

✅ Все тесты проходят

# URL Страниц

```
  MAIN = '/',
  CHAT = '/messenger/',
  AUTH = '/auth/',
  PROFILE = '/settings/',
```

## TODO

- [ ] Сейчас страницы открываются при указание в урле /messenger/, нужно доделать, чтобы и для /messenger вхождение было. Также и для профиля.
- [x] авторизацию в полном объеме (регистрация, авторизация, выход из системы);
- [x] работу с информацией пользователя (изменять данные пользователя, изменять аватар, изменять пароль);
- [x] работу с чатами (список чатов пользователя, создать новый чат, добавить пользователя в чат, удалить пользователя из чата).

## Возможные ошибки

Если ругается на @parcel/transformer-sass, что он не той версии. Можно удалить node_modules, dist и кэш парсела и снова установить зависимости. Если совсем не помогает, то сменить на 2.7.0.

## Дополнительно

- [Дизайн в Figma](https://www.figma.com/file/jF5fFFzgGOxQeB4CmKWTiE/Chat_external_link?node-id=0%3A1&t=hiTbvcfSm7jC5TVn-1)

2023-01-23 15:58 UTC, podlovchenko requested changes
Привет)

1. Нет ссылки на нетлифай в ридми
2. Нужно вернуть .github/workflows/tests.yml, который был удален в первом пулл реквесте

В остальном все здорово, хорошая работа)

2023-01-23 15:58 UTC, podlovchenko commented on src/api/auth.ts
> +export default new AuthAPI();
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2023-01-23 15:58 UTC, podlovchenko commented on src/api/profile.ts
> +    return requestInstance.put('/profile/avatar', { data, headers: { } });
Зачем передается пустой массив в headers?

2023-01-24 08:17 UTC, toropanov commented
✅ Замечания учтены. Спасибо за ревью

2023-01-24 09:25 UTC, toropanov commented
✅ Замечания учтены. Спасибо за ревью
✅ Тесты одолел

2023-01-24 09:42 UTC, podlovchenko approved these changes
Принято)

2023-03-04 08:06 UTC, merged